#!/bin/sh
#
# mod-sdk init script
#
### BEGIN INIT INFO
# Provides:          $mod-sdk
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start MOD SDK service
# Description:       Starts mod-sdk
### END INIT INFO

# Defaults
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/modsdk
OPTIONS=""
START_DAEMON=yes
DELAY_BEFORE_START=0
PIDFILE="/var/run/mod-sdk.pid"
test -f /etc/default/mod-sdk && . /etc/default/mod-sdk


if [ ! "x$START_DAEMON" = "xyes" -a ! "$1" = "stop" ]; then
        echo "Edit /etc/default/mod-sdk to start mod-sdk"
        exit 0
fi

test -f $DAEMON || exit 0

. /etc/init.d/functions

case "$1" in
        start)
                echo "Starting mod-sdk server:" "mod-sdk"
                sleep $DELAY_BEFORE_START
                if start-stop-daemon -b -S -o -m -p $PIDFILE -x $DAEMON -- $OPTIONS; then
                        success
                else
                        failure
                        exit 1
                fi
                ;;
        stop)
                echo "Stopping mod-sdk server:" "mod-sdk"
                if start-stop-daemon -K -o -p $PIDFILE ; then
                        rm -f $PIDFILE
                        success
                else
                        failure
                        exit 1
                fi
                ;;
        force-reload|restart)
                echo "Restarting mod-sdk service:" "mod-sdk"
                if ! start-stop-daemon -K -o -p $PIDFILE ; then
                        failure
                        exit 1
                fi
                rm -f $PIDFILE || true
                sleep $DELAY_BEFORE_START
                if start-stop-daemon -b -S -o -m -p $PIDFILE -x $DAEMON -- $OPTIONS; then
                        success
                else
                        failure
                        exit 1
                fi
                ;;
        try-restart)
                if test -e $PIDFILE ; then
                        pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
                        PIDDIR=/proc/$pid
                        if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${DAEMON}" ]; then
                                $0 restart
                                exit 0
                        fi
                fi
                test -f /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S*mod-sdk* && $0 start
                ;;
        awaken)
                echo "Awakening mod-sdk service:" "mod-sdk"
                if [ -s $PIDFILE ]; then
                        start-stop-daemon -K -s 10 -p $PIDFILE 
                        success
                        exit 0
                else
                        failure
                        exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/mod-sdk {start|stop|restart|force-reload|awaken|debug-run}"
                echo "  start - starts system-wide service"
                echo "  stop  - stops system-wide service"
                echo "  restart, force-reload - a new system-wide service"
                echo "  awaken - tell system-wide service to start a poll cycle immediately"
                exit 1
                ;;
esac

exit 0
